// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RubenAppFinal.Data;

#nullable disable

namespace RubenAppFinal.Migrations
{
    [DbContext(typeof(GimnasioContext))]
    partial class GimnasioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RubenAppFinal.Models.Clase", b =>
                {
                    b.Property<int>("ClaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaseId"));

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClaseId");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            ClaseId = 1,
                            EntrenadorId = 1,
                            Nivel = "Avanzado",
                            Nombre = "CrossFit Avanzado",
                            PrecioMensual = 50m
                        },
                        new
                        {
                            ClaseId = 2,
                            EntrenadorId = 2,
                            Nivel = "Básico",
                            Nombre = "Yoga Principiantes",
                            PrecioMensual = 30m
                        },
                        new
                        {
                            ClaseId = 3,
                            EntrenadorId = 3,
                            Nivel = "Intermedio",
                            Nombre = "Boxeo Intermedio",
                            PrecioMensual = 40m
                        },
                        new
                        {
                            ClaseId = 4,
                            EntrenadorId = 2,
                            Nivel = "Básico",
                            Nombre = "Pilates",
                            PrecioMensual = 35m
                        });
                });

            modelBuilder.Entity("RubenAppFinal.Models.Entrenador", b =>
                {
                    b.Property<int>("EntrenadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntrenadorId"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntrenadorId");

                    b.ToTable("Entrenadores");

                    b.HasData(
                        new
                        {
                            EntrenadorId = 1,
                            Especialidad = "CrossFit",
                            Nombre = "Carlos Ruiz"
                        },
                        new
                        {
                            EntrenadorId = 2,
                            Especialidad = "Yoga",
                            Nombre = "Laura Sánchez"
                        },
                        new
                        {
                            EntrenadorId = 3,
                            Especialidad = "Boxeo",
                            Nombre = "David López"
                        });
                });

            modelBuilder.Entity("RubenAppFinal.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscripcionId"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("InscripcionId");

                    b.HasIndex("ClaseId");

                    b.HasIndex("SocioId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            InscripcionId = 1,
                            ClaseId = 1,
                            FechaInicio = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 1
                        },
                        new
                        {
                            InscripcionId = 2,
                            ClaseId = 2,
                            FechaInicio = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 1
                        },
                        new
                        {
                            InscripcionId = 3,
                            ClaseId = 2,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 2
                        },
                        new
                        {
                            InscripcionId = 4,
                            ClaseId = 3,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 2
                        },
                        new
                        {
                            InscripcionId = 5,
                            ClaseId = 1,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 3
                        },
                        new
                        {
                            InscripcionId = 6,
                            ClaseId = 3,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 3
                        },
                        new
                        {
                            InscripcionId = 7,
                            ClaseId = 2,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 4
                        },
                        new
                        {
                            InscripcionId = 8,
                            ClaseId = 4,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 4
                        },
                        new
                        {
                            InscripcionId = 9,
                            ClaseId = 1,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 5
                        },
                        new
                        {
                            InscripcionId = 10,
                            ClaseId = 4,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 5
                        },
                        new
                        {
                            InscripcionId = 11,
                            ClaseId = 2,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 6
                        },
                        new
                        {
                            InscripcionId = 12,
                            ClaseId = 3,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 6
                        },
                        new
                        {
                            InscripcionId = 13,
                            ClaseId = 1,
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SocioId = 7
                        });
                });

            modelBuilder.Entity("RubenAppFinal.Models.Socio", b =>
                {
                    b.Property<int>("SocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocioId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            SocioId = 1,
                            Email = "carlos@email.com",
                            Nombre = "Carlos Pérez"
                        },
                        new
                        {
                            SocioId = 2,
                            Email = "ana@email.com",
                            Nombre = "Ana Gómez"
                        },
                        new
                        {
                            SocioId = 3,
                            Email = "luis@email.com",
                            Nombre = "Luis Martínez"
                        },
                        new
                        {
                            SocioId = 4,
                            Email = "marta@email.com",
                            Nombre = "Marta Díaz"
                        },
                        new
                        {
                            SocioId = 5,
                            Email = "javier@email.com",
                            Nombre = "Javier Torres"
                        },
                        new
                        {
                            SocioId = 6,
                            Email = "lucia@email.com",
                            Nombre = "Lucía Fernández"
                        },
                        new
                        {
                            SocioId = 7,
                            Email = "pedro@email.com",
                            Nombre = "Pedro Morales"
                        });
                });

            modelBuilder.Entity("RubenAppFinal.Models.Clase", b =>
                {
                    b.HasOne("RubenAppFinal.Models.Entrenador", "Entrenador")
                        .WithMany("Clases")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("RubenAppFinal.Models.Inscripcion", b =>
                {
                    b.HasOne("RubenAppFinal.Models.Clase", "Clase")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RubenAppFinal.Models.Socio", "Socio")
                        .WithMany("Inscripciones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("RubenAppFinal.Models.Clase", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("RubenAppFinal.Models.Entrenador", b =>
                {
                    b.Navigation("Clases");
                });

            modelBuilder.Entity("RubenAppFinal.Models.Socio", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
