// <auto-generated />
using System;
using ColoniasEspaciales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColoniasEspaciales.Migrations
{
    [DbContext(typeof(ColoniasContext))]
    [Migration("20251104173112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColoniasEspaciales.Models.Colonia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NivelSostenibilidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanetaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanetaId");

                    b.ToTable("Colonias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NivelSostenibilidad = "Alta",
                            Nombre = "Nova Terra",
                            PlanetaId = 1
                        },
                        new
                        {
                            Id = 2,
                            NivelSostenibilidad = "Media",
                            Nombre = "Viento Azul",
                            PlanetaId = 2
                        });
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.ColoniaRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ColoniaId")
                        .HasColumnType("int");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColoniaId");

                    b.HasIndex("RecursoId");

                    b.ToTable("ColoniaRecursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 5000,
                            ColoniaId = 1,
                            RecursoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 4000,
                            ColoniaId = 1,
                            RecursoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 3000,
                            ColoniaId = 2,
                            RecursoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 6000,
                            ColoniaId = 2,
                            RecursoId = 3
                        });
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColoniaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColoniaId");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColoniaId = 1,
                            Descripcion = "Una tormenta afecta las comunicaciones.",
                            Fecha = new DateTime(2124, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Tormenta Solar"
                        },
                        new
                        {
                            Id = 2,
                            ColoniaId = 2,
                            Descripcion = "Se ha encontrado un nuevo mineral.",
                            Fecha = new DateTime(2124, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Descubrimiento"
                        });
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Habitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColoniaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColoniaId");

                    b.ToTable("Habitantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColoniaId = 1,
                            Nombre = "Lucía Vega",
                            Rol = "Comandante"
                        },
                        new
                        {
                            Id = 2,
                            ColoniaId = 1,
                            Nombre = "Carlos Luna",
                            Rol = "Ingeniero"
                        },
                        new
                        {
                            Id = 3,
                            ColoniaId = 2,
                            Nombre = "Marta Sol",
                            Rol = "Bióloga"
                        });
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TemperaturaPromedio")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planetas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Aurelia",
                            TemperaturaPromedio = 22.5,
                            Tipo = "Terrestre"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Zephyria",
                            TemperaturaPromedio = -80.0,
                            Tipo = "Gaseoso"
                        });
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadTotal = 10000,
                            Nombre = "Agua"
                        },
                        new
                        {
                            Id = 2,
                            CantidadTotal = 8000,
                            Nombre = "Oxígeno"
                        },
                        new
                        {
                            Id = 3,
                            CantidadTotal = 12000,
                            Nombre = "Metal"
                        });
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Colonia", b =>
                {
                    b.HasOne("ColoniasEspaciales.Models.Planeta", "Planeta")
                        .WithMany("Colonias")
                        .HasForeignKey("PlanetaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Planeta");
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.ColoniaRecurso", b =>
                {
                    b.HasOne("ColoniasEspaciales.Models.Colonia", "Colonia")
                        .WithMany("ColoniaRecursos")
                        .HasForeignKey("ColoniaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ColoniasEspaciales.Models.Recurso", "Recurso")
                        .WithMany("ColoniaRecursos")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colonia");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Evento", b =>
                {
                    b.HasOne("ColoniasEspaciales.Models.Colonia", "Colonia")
                        .WithMany("Eventos")
                        .HasForeignKey("ColoniaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colonia");
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Habitante", b =>
                {
                    b.HasOne("ColoniasEspaciales.Models.Colonia", "Colonia")
                        .WithMany("Habitantes")
                        .HasForeignKey("ColoniaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colonia");
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Colonia", b =>
                {
                    b.Navigation("ColoniaRecursos");

                    b.Navigation("Eventos");

                    b.Navigation("Habitantes");
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Planeta", b =>
                {
                    b.Navigation("Colonias");
                });

            modelBuilder.Entity("ColoniasEspaciales.Models.Recurso", b =>
                {
                    b.Navigation("ColoniaRecursos");
                });
#pragma warning restore 612, 618
        }
    }
}
