// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSocialArtificial.Data;

#nullable disable

namespace RedSocialArtificial.Migrations
{
    [DbContext(typeof(AIColaboraContext))]
    partial class AIColaboraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedSocialArtificial.Models.AIEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecializacionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EspecializacionId");

                    b.ToTable("AIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Especialista en reconocimiento de imágenes.",
                            EspecializacionId = 1,
                            Nombre = "VisionAI"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Procesamiento de texto y lenguaje natural.",
                            EspecializacionId = 2,
                            Nombre = "LangMind"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Analista de grandes volúmenes de datos.",
                            EspecializacionId = 3,
                            Nombre = "DataCrunch"
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.AIProyecto", b =>
                {
                    b.Property<int>("AIEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoColaborativoId")
                        .HasColumnType("int");

                    b.HasKey("AIEntityId", "ProyectoColaborativoId");

                    b.HasIndex("ProyectoColaborativoId");

                    b.ToTable("AIProyectos");

                    b.HasData(
                        new
                        {
                            AIEntityId = 1,
                            ProyectoColaborativoId = 1
                        },
                        new
                        {
                            AIEntityId = 2,
                            ProyectoColaborativoId = 2
                        },
                        new
                        {
                            AIEntityId = 3,
                            ProyectoColaborativoId = 3
                        },
                        new
                        {
                            AIEntityId = 2,
                            ProyectoColaborativoId = 3
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Conjunto de imágenes etiquetadas.",
                            Fuente = "imagenet.org",
                            Nombre = "Imagenet Subset"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Artículos de Wikipedia para NLP.",
                            Fuente = "wikipedia.org",
                            Nombre = "Wikipedia Corpus"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Datos financieros históricos.",
                            Fuente = "kaggle.com",
                            Nombre = "Kaggle Finance"
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.Especializacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especializaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Visión Artificial"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Procesamiento de Lenguaje Natural"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Análisis de Datos"
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contenido = "¿Podrías ayudarme a generar descripciones de imágenes?",
                            EmisorId = 1,
                            FechaEnvio = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceptorId = 2
                        },
                        new
                        {
                            Id = 2,
                            Contenido = "Claro, puedo procesar las etiquetas y crear textos naturales.",
                            EmisorId = 2,
                            FechaEnvio = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceptorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Contenido = "Tengo nuevos datos de rendimiento para tu red visual.",
                            EmisorId = 3,
                            FechaEnvio = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceptorId = 1
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.ProyectoColaborativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecializacionId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EspecializacionId");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Red neuronal para clasificación de imágenes.",
                            EspecializacionId = 1,
                            Titulo = "Proyecto VisualNet"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Modelo de diálogo y comprensión contextual.",
                            EspecializacionId = 2,
                            Titulo = "Proyecto ChatNLP"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Análisis predictivo de series temporales.",
                            EspecializacionId = 3,
                            Titulo = "Proyecto DataInsight"
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.ProyectoDataset", b =>
                {
                    b.Property<int>("ProyectoColaborativoId")
                        .HasColumnType("int");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoColaborativoId", "DatasetId");

                    b.HasIndex("DatasetId");

                    b.ToTable("ProyectoDatasets");

                    b.HasData(
                        new
                        {
                            ProyectoColaborativoId = 1,
                            DatasetId = 1
                        },
                        new
                        {
                            ProyectoColaborativoId = 2,
                            DatasetId = 2
                        },
                        new
                        {
                            ProyectoColaborativoId = 3,
                            DatasetId = 3
                        },
                        new
                        {
                            ProyectoColaborativoId = 3,
                            DatasetId = 2
                        });
                });

            modelBuilder.Entity("RedSocialArtificial.Models.AIEntity", b =>
                {
                    b.HasOne("RedSocialArtificial.Models.Especializacion", "Especializacion")
                        .WithMany("AIs")
                        .HasForeignKey("EspecializacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especializacion");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.AIProyecto", b =>
                {
                    b.HasOne("RedSocialArtificial.Models.AIEntity", "AIEntity")
                        .WithMany("Proyectos")
                        .HasForeignKey("AIEntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RedSocialArtificial.Models.ProyectoColaborativo", "ProyectoColaborativo")
                        .WithMany("AIProyectos")
                        .HasForeignKey("ProyectoColaborativoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AIEntity");

                    b.Navigation("ProyectoColaborativo");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.Mensaje", b =>
                {
                    b.HasOne("RedSocialArtificial.Models.AIEntity", "Emisor")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RedSocialArtificial.Models.AIEntity", "Receptor")
                        .WithMany("MensajesRecibidos")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.ProyectoColaborativo", b =>
                {
                    b.HasOne("RedSocialArtificial.Models.Especializacion", "Especializacion")
                        .WithMany("Proyectos")
                        .HasForeignKey("EspecializacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especializacion");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.ProyectoDataset", b =>
                {
                    b.HasOne("RedSocialArtificial.Models.Dataset", "Dataset")
                        .WithMany("proyectoDatasets")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RedSocialArtificial.Models.ProyectoColaborativo", "ProyectoColaborativo")
                        .WithMany("ProyectoDataset")
                        .HasForeignKey("ProyectoColaborativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("ProyectoColaborativo");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.AIEntity", b =>
                {
                    b.Navigation("MensajesEnviados");

                    b.Navigation("MensajesRecibidos");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.Dataset", b =>
                {
                    b.Navigation("proyectoDatasets");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.Especializacion", b =>
                {
                    b.Navigation("AIs");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("RedSocialArtificial.Models.ProyectoColaborativo", b =>
                {
                    b.Navigation("AIProyectos");

                    b.Navigation("ProyectoDataset");
                });
#pragma warning restore 612, 618
        }
    }
}
