// <auto-generated />
using System;
using EnergiaRenovables.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergiaRenovables.Migrations
{
    [DbContext(typeof(RenovableContext))]
    [Migration("20251104224010_Null-Fixed")]
    partial class NullFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergiaRenovables.Models.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EnergiaGeneradaMWh")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Informes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnergiaGeneradaMWh = 1200.0,
                            Fecha = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProyectoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnergiaGeneradaMWh = 2300.0,
                            Fecha = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProyectoId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnergiaGeneradaMWh = 3100.0,
                            Fecha = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProyectoId = 3
                        },
                        new
                        {
                            Id = 4,
                            EnergiaGeneradaMWh = 1800.0,
                            Fecha = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProyectoId = 4
                        },
                        new
                        {
                            Id = 5,
                            EnergiaGeneradaMWh = 2600.0,
                            Fecha = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProyectoId = 5
                        });
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Inversion", b =>
                {
                    b.Property<int>("InversorId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<double>("MontoInvertido")
                        .HasColumnType("float");

                    b.HasKey("InversorId", "ProyectoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Inversiones");

                    b.HasData(
                        new
                        {
                            InversorId = 1,
                            ProyectoId = 1,
                            MontoInvertido = 250000.0
                        },
                        new
                        {
                            InversorId = 2,
                            ProyectoId = 2,
                            MontoInvertido = 400000.0
                        },
                        new
                        {
                            InversorId = 3,
                            ProyectoId = 3,
                            MontoInvertido = 600000.0
                        },
                        new
                        {
                            InversorId = 4,
                            ProyectoId = 4,
                            MontoInvertido = 300000.0
                        },
                        new
                        {
                            InversorId = 5,
                            ProyectoId = 5,
                            MontoInvertido = 500000.0
                        });
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Inversor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CapitalDisponible")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inversores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapitalDisponible = 2000000.0,
                            Nombre = "Inversiones Globales S.A."
                        },
                        new
                        {
                            Id = 2,
                            CapitalDisponible = 1500000.0,
                            Nombre = "EcoCapital"
                        },
                        new
                        {
                            Id = 3,
                            CapitalDisponible = 1800000.0,
                            Nombre = "GreenFund"
                        },
                        new
                        {
                            Id = 4,
                            CapitalDisponible = 1200000.0,
                            Nombre = "SolarTrust"
                        },
                        new
                        {
                            Id = 5,
                            CapitalDisponible = 2200000.0,
                            Nombre = "BlueEnergy"
                        });
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("InversionTotal")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEnergiaId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoEnergiaId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InversionTotal = 500000.0,
                            Nombre = "Solar Sur",
                            TipoEnergiaId = 1,
                            UbicacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            InversionTotal = 850000.0,
                            Nombre = "Viento Norte",
                            TipoEnergiaId = 2,
                            UbicacionId = 2
                        },
                        new
                        {
                            Id = 3,
                            InversionTotal = 1200000.0,
                            Nombre = "Río Verde",
                            TipoEnergiaId = 3,
                            UbicacionId = 3
                        },
                        new
                        {
                            Id = 4,
                            InversionTotal = 650000.0,
                            Nombre = "Calor Tierra",
                            TipoEnergiaId = 4,
                            UbicacionId = 4
                        },
                        new
                        {
                            Id = 5,
                            InversionTotal = 900000.0,
                            Nombre = "BioFuturo",
                            TipoEnergiaId = 5,
                            UbicacionId = 5
                        });
                });

            modelBuilder.Entity("EnergiaRenovables.Models.TipoEnergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEnergias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Solar"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Eólica"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Hidráulica"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Geotérmica"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Biomasa"
                        });
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ciudad = "Sevilla",
                            Pais = "España"
                        },
                        new
                        {
                            Id = 2,
                            Ciudad = "Hamburgo",
                            Pais = "Alemania"
                        },
                        new
                        {
                            Id = 3,
                            Ciudad = "Santiago",
                            Pais = "Chile"
                        },
                        new
                        {
                            Id = 4,
                            Ciudad = "Lisboa",
                            Pais = "Portugal"
                        },
                        new
                        {
                            Id = 5,
                            Ciudad = "Toronto",
                            Pais = "Canadá"
                        });
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Informe", b =>
                {
                    b.HasOne("EnergiaRenovables.Models.Proyecto", "Proyecto")
                        .WithMany("Informes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Inversion", b =>
                {
                    b.HasOne("EnergiaRenovables.Models.Inversor", "Inversor")
                        .WithMany("Inversiones")
                        .HasForeignKey("InversorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergiaRenovables.Models.Proyecto", "Proyecto")
                        .WithMany("Inversiones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inversor");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Proyecto", b =>
                {
                    b.HasOne("EnergiaRenovables.Models.TipoEnergia", "TipoEnergia")
                        .WithMany("Proyectos")
                        .HasForeignKey("TipoEnergiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergiaRenovables.Models.Ubicacion", "Ubicacion")
                        .WithMany("Proyectos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEnergia");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Inversor", b =>
                {
                    b.Navigation("Inversiones");
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Proyecto", b =>
                {
                    b.Navigation("Informes");

                    b.Navigation("Inversiones");
                });

            modelBuilder.Entity("EnergiaRenovables.Models.TipoEnergia", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("EnergiaRenovables.Models.Ubicacion", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
