// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSocialIA.Data;

#nullable disable

namespace RedSocialIA.Migrations
{
    [DbContext(typeof(RedAIDbContext))]
    [Migration("20251103110614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIProyectoColaborativo", b =>
                {
                    b.Property<int>("AIsAiId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectosColaborativosProyectoColaborativoId")
                        .HasColumnType("int");

                    b.HasKey("AIsAiId", "ProyectosColaborativosProyectoColaborativoId");

                    b.HasIndex("ProyectosColaborativosProyectoColaborativoId");

                    b.ToTable("AIProyectoColaborativo");
                });

            modelBuilder.Entity("DatasetProyectoColaborativo", b =>
                {
                    b.Property<int>("DatasetsDatasetId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectosColaborativosProyectoColaborativoId")
                        .HasColumnType("int");

                    b.HasKey("DatasetsDatasetId", "ProyectosColaborativosProyectoColaborativoId");

                    b.HasIndex("ProyectosColaborativosProyectoColaborativoId");

                    b.ToTable("DatasetProyectoColaborativo");
                });

            modelBuilder.Entity("RedSocialIA.Model.AI", b =>
                {
                    b.Property<int>("AiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecializacionID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelInteligencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiId");

                    b.HasIndex("EspecializacionID");

                    b.ToTable("AIs");
                });

            modelBuilder.Entity("RedSocialIA.Model.Dataset", b =>
                {
                    b.Property<int>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatasetId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatasetId");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("RedSocialIA.Model.Especializacion", b =>
                {
                    b.Property<int>("EspecializacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecializacionID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecializacionID");

                    b.ToTable("Especializaciones");
                });

            modelBuilder.Entity("RedSocialIA.Model.Mensaje", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensajeId"));

                    b.Property<int>("AiId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("MensajeId");

                    b.HasIndex("AiId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("RedSocialIA.Model.ProyectoColaborativo", b =>
                {
                    b.Property<int>("ProyectoColaborativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoColaborativoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProyectoColaborativoId");

                    b.ToTable("ProyectosColaborativos");
                });

            modelBuilder.Entity("AIProyectoColaborativo", b =>
                {
                    b.HasOne("RedSocialIA.Model.AI", null)
                        .WithMany()
                        .HasForeignKey("AIsAiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedSocialIA.Model.ProyectoColaborativo", null)
                        .WithMany()
                        .HasForeignKey("ProyectosColaborativosProyectoColaborativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatasetProyectoColaborativo", b =>
                {
                    b.HasOne("RedSocialIA.Model.Dataset", null)
                        .WithMany()
                        .HasForeignKey("DatasetsDatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedSocialIA.Model.ProyectoColaborativo", null)
                        .WithMany()
                        .HasForeignKey("ProyectosColaborativosProyectoColaborativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RedSocialIA.Model.AI", b =>
                {
                    b.HasOne("RedSocialIA.Model.Especializacion", "Especializacion")
                        .WithMany("AIs")
                        .HasForeignKey("EspecializacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especializacion");
                });

            modelBuilder.Entity("RedSocialIA.Model.Mensaje", b =>
                {
                    b.HasOne("RedSocialIA.Model.AI", "AI")
                        .WithMany()
                        .HasForeignKey("AiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AI");
                });

            modelBuilder.Entity("RedSocialIA.Model.Especializacion", b =>
                {
                    b.Navigation("AIs");
                });
#pragma warning restore 612, 618
        }
    }
}
