// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaEFC.Data;

#nullable disable

namespace TiendaEFC.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20251109105011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaEFC.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido = "López",
                            Direccion = "C/ Alcalá 10",
                            Nombre = "Ana",
                            Telefono = "600123456"
                        },
                        new
                        {
                            ClienteId = 2,
                            Apellido = "Pérez",
                            Direccion = "Av. de América 80",
                            Nombre = "Luis",
                            Telefono = "600654321"
                        },
                        new
                        {
                            ClienteId = 3,
                            Apellido = "Gómez",
                            Direccion = "C/ Serrano 42",
                            Nombre = "Marta",
                            Telefono = "601998877"
                        },
                        new
                        {
                            ClienteId = 4,
                            Apellido = "Ruiz",
                            Direccion = "C/ Toledo 14",
                            Nombre = "Carlos",
                            Telefono = "602112233"
                        },
                        new
                        {
                            ClienteId = 5,
                            Apellido = "Fernández",
                            Direccion = "C/ Princesa 5",
                            Nombre = "Elena",
                            Telefono = "603445566"
                        });
                });

            modelBuilder.Entity("TiendaEFC.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("CompraId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Compras");

                    b.HasData(
                        new
                        {
                            CompraId = 1,
                            ClienteId = 1,
                            FechaCompra = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 1
                        },
                        new
                        {
                            CompraId = 2,
                            ClienteId = 2,
                            FechaCompra = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 3
                        },
                        new
                        {
                            CompraId = 3,
                            ClienteId = 3,
                            FechaCompra = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 2
                        },
                        new
                        {
                            CompraId = 4,
                            ClienteId = 4,
                            FechaCompra = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 5
                        },
                        new
                        {
                            CompraId = 5,
                            ClienteId = 5,
                            FechaCompra = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 4
                        },
                        new
                        {
                            CompraId = 6,
                            ClienteId = 1,
                            FechaCompra = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 6
                        },
                        new
                        {
                            CompraId = 7,
                            ClienteId = 3,
                            FechaCompra = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 1
                        },
                        new
                        {
                            CompraId = 8,
                            ClienteId = 2,
                            FechaCompra = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = 2
                        });
                });

            modelBuilder.Entity("TiendaEFC.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroExistencias")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Codigo = "P001",
                            Descripcion = "Portátil HP 15\"",
                            NumeroExistencias = 25,
                            Precio = 699.99000000000001
                        },
                        new
                        {
                            ProductoId = 2,
                            Codigo = "P002",
                            Descripcion = "Ratón inalámbrico Logitech",
                            NumeroExistencias = 150,
                            Precio = 29.899999999999999
                        },
                        new
                        {
                            ProductoId = 3,
                            Codigo = "P003",
                            Descripcion = "Teclado mecánico Corsair",
                            NumeroExistencias = 75,
                            Precio = 89.989999999999995
                        },
                        new
                        {
                            ProductoId = 4,
                            Codigo = "P004",
                            Descripcion = "Monitor Samsung 27\"",
                            NumeroExistencias = 40,
                            Precio = 229.5
                        },
                        new
                        {
                            ProductoId = 5,
                            Codigo = "P005",
                            Descripcion = "Impresora HP LaserJet",
                            NumeroExistencias = 30,
                            Precio = 179.0
                        },
                        new
                        {
                            ProductoId = 6,
                            Codigo = "P006",
                            Descripcion = "Auriculares Sony WH-1000XM4",
                            NumeroExistencias = 60,
                            Precio = 299.99000000000001
                        });
                });

            modelBuilder.Entity("TiendaEFC.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            ProveedorId = 1,
                            Direccion = "C/ Mayor 15",
                            Nombre = "ElectroMax",
                            Provincia = "Madrid",
                            Telefono = "911223344"
                        },
                        new
                        {
                            ProveedorId = 2,
                            Direccion = "Av. América 22",
                            Nombre = "TechPlus",
                            Provincia = "Madrid",
                            Telefono = "912334455"
                        },
                        new
                        {
                            ProveedorId = 3,
                            Direccion = "C/ Gran Vía 120",
                            Nombre = "Distribuciones Vega",
                            Provincia = "Toledo",
                            Telefono = "925123456"
                        },
                        new
                        {
                            ProveedorId = 4,
                            Direccion = "Polígono El Olivar",
                            Nombre = "Logística Sur",
                            Provincia = "Sevilla",
                            Telefono = "954998877"
                        });
                });

            modelBuilder.Entity("TiendaEFC.Models.Suministro", b =>
                {
                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("ProveedorId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Suministros");

                    b.HasData(
                        new
                        {
                            ProveedorId = 1,
                            ProductoId = 1
                        },
                        new
                        {
                            ProveedorId = 1,
                            ProductoId = 2
                        },
                        new
                        {
                            ProveedorId = 2,
                            ProductoId = 3
                        },
                        new
                        {
                            ProveedorId = 2,
                            ProductoId = 4
                        },
                        new
                        {
                            ProveedorId = 3,
                            ProductoId = 5
                        },
                        new
                        {
                            ProveedorId = 4,
                            ProductoId = 6
                        },
                        new
                        {
                            ProveedorId = 3,
                            ProductoId = 2
                        },
                        new
                        {
                            ProveedorId = 4,
                            ProductoId = 4
                        });
                });

            modelBuilder.Entity("TiendaEFC.Models.Compra", b =>
                {
                    b.HasOne("TiendaEFC.Models.Cliente", "Cliente")
                        .WithMany("Compras")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiendaEFC.Models.Producto", "Producto")
                        .WithMany("Compras")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiendaEFC.Models.Suministro", b =>
                {
                    b.HasOne("TiendaEFC.Models.Producto", "Producto")
                        .WithMany("Suministros")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiendaEFC.Models.Proveedor", "Proveedor")
                        .WithMany("Suministros")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("TiendaEFC.Models.Cliente", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("TiendaEFC.Models.Producto", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Suministros");
                });

            modelBuilder.Entity("TiendaEFC.Models.Proveedor", b =>
                {
                    b.Navigation("Suministros");
                });
#pragma warning restore 612, 618
        }
    }
}
