// <auto-generated />
using System;
using CriptomonedasEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CriptomonedasEF.Migrations
{
    [DbContext(typeof(CriptoContext))]
    [Migration("20251104185058_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CriptomonedasEF.Models.Criptomoneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorActual")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Criptomonedas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Bitcoin",
                            Simbolo = "BTC",
                            ValorActual = 65000.0
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ethereum",
                            Simbolo = "ETH",
                            ValorActual = 3400.5
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cardano",
                            Simbolo = "ADA",
                            ValorActual = 0.45000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Solana",
                            Simbolo = "SOL",
                            ValorActual = 180.75
                        });
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("CriptomonedaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriptomonedaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Operaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 0.029999999999999999,
                            CriptomonedaId = 1,
                            Fecha = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoOperacion = "Compra",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1.0,
                            CriptomonedaId = 3,
                            Fecha = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoOperacion = "Venta",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 2.0,
                            CriptomonedaId = 2,
                            Fecha = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoOperacion = "Compra",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 0.070000000000000007,
                            CriptomonedaId = 1,
                            Fecha = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoOperacion = "Compra",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Portafolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CantidadActual")
                        .HasColumnType("float");

                    b.Property<int>("CriptomonedaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriptomonedaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Portafolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadActual = 0.050000000000000003,
                            CriptomonedaId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            CantidadActual = 2.2999999999999998,
                            CriptomonedaId = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            CantidadActual = 1000.0,
                            CriptomonedaId = 3,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 4,
                            CantidadActual = 5.5,
                            CriptomonedaId = 4,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 5,
                            CantidadActual = 0.12,
                            CriptomonedaId = 1,
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaldoVirtual")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@crypto.com",
                            Nombre = "Alice",
                            SaldoVirtual = 2500.0
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@crypto.com",
                            Nombre = "Bob",
                            SaldoVirtual = 1200.5
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@crypto.com",
                            Nombre = "Charlie",
                            SaldoVirtual = 3400.75
                        });
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Operacion", b =>
                {
                    b.HasOne("CriptomonedasEF.Models.Criptomoneda", "Criptomoneda")
                        .WithMany("Operaciones")
                        .HasForeignKey("CriptomonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriptomonedasEF.Models.Usuario", "Usuario")
                        .WithMany("Operaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criptomoneda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Portafolio", b =>
                {
                    b.HasOne("CriptomonedasEF.Models.Criptomoneda", "Criptomoneda")
                        .WithMany("Portafolios")
                        .HasForeignKey("CriptomonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriptomonedasEF.Models.Usuario", "Usuario")
                        .WithMany("Portafolios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criptomoneda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Criptomoneda", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("Portafolios");
                });

            modelBuilder.Entity("CriptomonedasEF.Models.Usuario", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("Portafolios");
                });
#pragma warning restore 612, 618
        }
    }
}
