// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservaHoteles.Data;

#nullable disable

namespace ReservaHoteles.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20251110110537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservaHoteles.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TipoIVA")
                        .HasColumnType("float");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descripcion = "Tres Estrellas",
                            TipoIVA = 10.0
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descripcion = "Cuatro Estrellas",
                            TipoIVA = 10.0
                        },
                        new
                        {
                            CategoriaId = 3,
                            Descripcion = "Cinco Estrellas",
                            TipoIVA = 21.0
                        });
                });

            modelBuilder.Entity("ReservaHoteles.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreClienteAgencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Direccion = "Calle Luna 5",
                            Nombre = "Carlos Gómez",
                            Telefono = "600112233",
                            TipoCliente = "Particular"
                        },
                        new
                        {
                            ClienteId = 2,
                            Direccion = "Av. Sol 23",
                            Nombre = "Laura Pérez",
                            Telefono = "600223344",
                            TipoCliente = "Particular"
                        },
                        new
                        {
                            ClienteId = 3,
                            Direccion = "Calle Flor 8",
                            Nombre = "Antonio Ruiz",
                            Telefono = "600334455",
                            TipoCliente = "Particular"
                        },
                        new
                        {
                            ClienteId = 4,
                            Direccion = "Plaza Norte 4",
                            Nombre = "María López",
                            Telefono = "600445566",
                            TipoCliente = "Particular"
                        },
                        new
                        {
                            ClienteId = 5,
                            Direccion = "Calle Prado 7",
                            Nombre = "Pedro Jiménez",
                            Telefono = "600556677",
                            TipoCliente = "Particular"
                        },
                        new
                        {
                            ClienteId = 6,
                            Direccion = "Calle Comercio 22",
                            Nombre = "Viajes SolTour",
                            NombreClienteAgencia = "Marta Díaz",
                            Telefono = "910223344",
                            TipoCliente = "Agencia"
                        },
                        new
                        {
                            ClienteId = 7,
                            Direccion = "Av. Europa 18",
                            Nombre = "Aventuras Travel",
                            NombreClienteAgencia = "Javier Cano",
                            Telefono = "910334455",
                            TipoCliente = "Agencia"
                        },
                        new
                        {
                            ClienteId = 8,
                            Direccion = "Calle Jardín 9",
                            Nombre = "HolidayExpress",
                            NombreClienteAgencia = "Lucía Torres",
                            Telefono = "910445566",
                            TipoCliente = "Agencia"
                        },
                        new
                        {
                            ClienteId = 9,
                            Direccion = "Av. Central 12",
                            Nombre = "GlobalTour",
                            NombreClienteAgencia = "David Martín",
                            Telefono = "910556677",
                            TipoCliente = "Agencia"
                        },
                        new
                        {
                            ClienteId = 10,
                            Direccion = "Paseo del Arte 3",
                            Nombre = "TravelPro",
                            NombreClienteAgencia = "Elena Ramos",
                            Telefono = "910667788",
                            TipoCliente = "Agencia"
                        });
                });

            modelBuilder.Entity("ReservaHoteles.Models.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitacionId"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("TipoHabitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabitacionId");

                    b.HasIndex("HotelId");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            HabitacionId = 1,
                            HotelId = 1,
                            Numero = 101,
                            TipoHabitacion = "Individual"
                        },
                        new
                        {
                            HabitacionId = 2,
                            HotelId = 1,
                            Numero = 102,
                            TipoHabitacion = "Doble"
                        },
                        new
                        {
                            HabitacionId = 3,
                            HotelId = 2,
                            Numero = 201,
                            TipoHabitacion = "Suite"
                        },
                        new
                        {
                            HabitacionId = 4,
                            HotelId = 2,
                            Numero = 202,
                            TipoHabitacion = "Doble"
                        },
                        new
                        {
                            HabitacionId = 5,
                            HotelId = 3,
                            Numero = 301,
                            TipoHabitacion = "Individual"
                        },
                        new
                        {
                            HabitacionId = 6,
                            HotelId = 3,
                            Numero = 302,
                            TipoHabitacion = "Suite"
                        });
                });

            modelBuilder.Entity("ReservaHoteles.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaConstruccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Hoteles");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            CategoriaId = 1,
                            Direccion = "Calle Mayor 10",
                            FechaConstruccion = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Hotel Sol",
                            Telefono = "911223344"
                        },
                        new
                        {
                            HotelId = 2,
                            CategoriaId = 3,
                            Direccion = "Av. Castellana 200",
                            FechaConstruccion = new DateTime(2005, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gran Palace",
                            Telefono = "912334455"
                        },
                        new
                        {
                            HotelId = 3,
                            CategoriaId = 2,
                            Direccion = "Paseo del Mar 22",
                            FechaConstruccion = new DateTime(2010, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Costa Azul",
                            Telefono = "933556677"
                        });
                });

            modelBuilder.Entity("ReservaHoteles.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaId = 1,
                            ClienteId = 1,
                            FechaFin = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 1,
                            Precio = 400.0
                        },
                        new
                        {
                            ReservaId = 2,
                            ClienteId = 1,
                            FechaFin = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 2,
                            Precio = 420.0
                        },
                        new
                        {
                            ReservaId = 3,
                            ClienteId = 2,
                            FechaFin = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 2,
                            Precio = 250.0
                        },
                        new
                        {
                            ReservaId = 4,
                            ClienteId = 3,
                            FechaFin = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 3,
                            Precio = 700.0
                        },
                        new
                        {
                            ReservaId = 5,
                            ClienteId = 4,
                            FechaFin = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 4,
                            Precio = 300.0
                        },
                        new
                        {
                            ReservaId = 6,
                            ClienteId = 5,
                            FechaFin = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 5,
                            Precio = 500.0
                        },
                        new
                        {
                            ReservaId = 7,
                            ClienteId = 2,
                            FechaFin = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 1,
                            Precio = 450.0
                        },
                        new
                        {
                            ReservaId = 8,
                            ClienteId = 3,
                            FechaFin = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 3,
                            Precio = 520.0
                        },
                        new
                        {
                            ReservaId = 9,
                            ClienteId = 6,
                            FechaFin = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 1,
                            Precio = 350.0
                        },
                        new
                        {
                            ReservaId = 10,
                            ClienteId = 6,
                            FechaFin = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 2,
                            Precio = 600.0
                        },
                        new
                        {
                            ReservaId = 11,
                            ClienteId = 7,
                            FechaFin = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 3,
                            Precio = 600.0
                        },
                        new
                        {
                            ReservaId = 12,
                            ClienteId = 8,
                            FechaFin = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 3,
                            Precio = 950.0
                        },
                        new
                        {
                            ReservaId = 13,
                            ClienteId = 8,
                            FechaFin = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 4,
                            Precio = 980.0
                        },
                        new
                        {
                            ReservaId = 14,
                            ClienteId = 9,
                            FechaFin = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 4,
                            Precio = 800.0
                        },
                        new
                        {
                            ReservaId = 15,
                            ClienteId = 10,
                            FechaFin = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 5,
                            Precio = 280.0
                        },
                        new
                        {
                            ReservaId = 16,
                            ClienteId = 7,
                            FechaFin = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 6,
                            Precio = 310.0
                        },
                        new
                        {
                            ReservaId = 17,
                            ClienteId = 8,
                            FechaFin = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 6,
                            Precio = 400.0
                        },
                        new
                        {
                            ReservaId = 18,
                            ClienteId = 9,
                            FechaFin = new DateTime(2025, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 2,
                            Precio = 390.0
                        },
                        new
                        {
                            ReservaId = 19,
                            ClienteId = 6,
                            FechaFin = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 5,
                            Precio = 500.0
                        },
                        new
                        {
                            ReservaId = 20,
                            ClienteId = 10,
                            FechaFin = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 4,
                            Precio = 720.0
                        });
                });

            modelBuilder.Entity("ReservaHoteles.Models.Habitacion", b =>
                {
                    b.HasOne("ReservaHoteles.Models.Hotel", "Hotel")
                        .WithMany("Habitaciones")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ReservaHoteles.Models.Hotel", b =>
                {
                    b.HasOne("ReservaHoteles.Models.Categoria", "Categoria")
                        .WithMany("Hoteles")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ReservaHoteles.Models.Reserva", b =>
                {
                    b.HasOne("ReservaHoteles.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservaHoteles.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("ReservaHoteles.Models.Categoria", b =>
                {
                    b.Navigation("Hoteles");
                });

            modelBuilder.Entity("ReservaHoteles.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservaHoteles.Models.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservaHoteles.Models.Hotel", b =>
                {
                    b.Navigation("Habitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
