// <auto-generated />
using System;
using LibreriaAsync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaAsync.Migrations
{
    [DbContext(typeof(LibreriaDBContext))]
    [Migration("20251104133549_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaAsync.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            Nacionalidad = "Colombia",
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            AutorId = 2,
                            Nacionalidad = "Reino Unido",
                            Nombre = "Jane Austen"
                        },
                        new
                        {
                            AutorId = 3,
                            Nacionalidad = "Japón",
                            Nombre = "Haruki Murakami"
                        });
                });

            modelBuilder.Entity("LibreriaAsync.Models.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibroId");

                    b.HasIndex("AutorId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AutorId = 1,
                            Genero = "Realismo mágico",
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            LibroId = 2,
                            AutorId = 1,
                            Genero = "Romance",
                            Titulo = "El Amor en los Tiempos del Cólera"
                        },
                        new
                        {
                            LibroId = 3,
                            AutorId = 2,
                            Genero = "Romance",
                            Titulo = "Orgullo y Prejuicio"
                        },
                        new
                        {
                            LibroId = 4,
                            AutorId = 3,
                            Genero = "Ficción surrealista",
                            Titulo = "Kafka en la Orilla"
                        });
                });

            modelBuilder.Entity("LibreriaAsync.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrestamoId");

                    b.HasIndex("LibroId");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            FechaPrestamo = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 1,
                            Usuario = "María López"
                        },
                        new
                        {
                            PrestamoId = 2,
                            FechaDevolucion = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 3,
                            Usuario = "Juan Pérez"
                        });
                });

            modelBuilder.Entity("LibreriaAsync.Models.Libro", b =>
                {
                    b.HasOne("LibreriaAsync.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("LibreriaAsync.Models.Prestamo", b =>
                {
                    b.HasOne("LibreriaAsync.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("LibreriaAsync.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("LibreriaAsync.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
